apiVersion: v1
kind: Secret
metadata:
  name: project-management-secrets
  namespace: project-management
type: Opaque
stringData:
  JWT_SECRET: "your-jwt-secret"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  USER_AUTH_DATABASE_URL: "postgresql://user:password@user-db:5432/user_auth_db"
  WORKSPACE_DATABASE_URL: "postgresql://user:password@workspace-db:5432/workspace_db"
  PROJECT_TASK_DATABASE_URL: "postgresql://user:password@project-task-db:5432/project_task_db"
